Foundation_English = float(input("Foundation: "))
General_Business = float(input("General Business: "))
Introduction_to_Computer_Systems = float(input("Introduction to Computer Systems: "))
Computer_Programming = float(input("Computer Programming: "))

print("-- Your Score --")
print("----------------------------------------")
print("Foundation English:", Foundation_English , )
print("General Business:", General_Business)
print("Introduction to Computer Systems:", Introduction_to_Computer_Systems)
print("Computer Programming:", Computer_Programming)
print("----------------------------------------")